spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 200MB
  datasource:
    name: souerce
    url: jdbc:mysql://localhost:3306/book?useUnicode=true&allowPublicKeyRetrieval=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: 123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  mvc:
    view:
      prefix: /
      suffix: .html
  jmx:
    enabled: false
  application:
    name: rabbitmq-service
    rabbitmq:
      addresses: 127.0.0.1:5672
      username: guest
      password: guest
      publisher-returns: true
      publisher-confirms: true
      template:
        mandatory: true
      listener:
        simple:
          acknowledge-mode: manual
          default-requeue-rejected: false
          concurrency: 1
          max-concurrency: 1
          prefetch: 1
          retry:
            enabled: true

mybatis:
  mapper-locations: classpath:mapping/*xml
  typeAliasesPackage: com.magician.book.pojo

logging:
  level:
    com.magician.book.dao: debug

